### ISSUE TITLE
sleep大于7s会被阻塞,循环不能正常执行

### ISSUE THREAD

**Issue by caidaoli** [yyzybb537/libgo#101]
` go[]{
        for(;;){
            printf("test\n");
            sleep(7);//小于7都能正常
        }
    };
    co_sched.Start();`
最新代码，osx和ubuntu测试循环不能正常运行

**Comment by yyzybb537** [comment]
确实如此，可能定时器有bug，我查一下看看

**Comment by yyzybb537** [comment]
已证实是多级时间轮定时器的一个bug.  2级以上的轮子没有正确触发，所以7s以上的定时器无法生效，刚刚临时将精度提到1ms，这个改动可以让1min内的定时器都恢复正常。

建议先更新一下，稍后我将彻底修复这个bug

**Comment by yyzybb537** [comment]
感谢提交bug，问题已经修复，并且增加了sleep(8)的单元测试
