### ISSUE TITLE
3.0已经有在实际项目中使用了吗？

### ISSUE THREAD

**Issue by mlkt** [yyzybb537/libgo#102]
3.0已经有在实际项目中使用了吗？没有的话原计划是打算用在哪里的？

**Comment by yyzybb537** [comment]
3.0刚刚发布不久，目前仅有一两个项目更新了3.0。

1.libgo-3.0新增的协程池功能，可以用在任何需要使用线程池的地方，尤其在“mysql访问”的线程池上有着极大的优化（具体见Readme和教程）
2.我们自家的项目，后续会考虑使用libgo3.0替换旧版的协程库

3.0在性能、架构、功能三个方面，相比2.9都有巨大的提升，如果你正在使用2.x，建议尝试升级3.0. （Linux和Mac可以升级，Windows还要再等等）
