### ISSUE TITLE
co_yield 异常crash

### ISSUE THREAD

**Issue by dearbird** [yyzybb537/libgo#105]
最近尝试迁移到3.0版本，程序老是跑一下就coredump，跟踪调试了下，把所有co_yield换成co_sleep(0)，就不会有问题。

另外写了测试代码验证了下，基本确定。
TEST(Coroutine, success2)
{
    std::atomic<uint32_t> count{0};

    auto func = [&]() {
        co_yield; // crash
        co_sleep(100);
        count--;
    };

    auto test = [&]() {
        for (int i = 0; i < 10000; ++i)
        {
            count++;
            go func;
        }

        while (count > 0)
        {
            co_sleep(10);
        }
        // EXPECT_EQ(count, 0);

        co_sched.Stop();
    };

    go test;

    co_sched.Start();
}

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff693c700 (LWP 29310)]
0x00007ffff7b9ef66 in jump_fcontext () from /work/RLL/libs/libgo/lib/liblibgo.so

**Comment by yyzybb537** [comment]
你链接到了旧版的so，清理后重装就好了

**Comment by dearbird** [comment]
ldd看了下，链接的路径是对的，3.0的库重新编译覆盖确认ok，仍然会crash。

**Comment by dearbird** [comment]
会不会是跟虚拟机有关系？ 我目前是virtual box 虚拟机，centos7.5

**Comment by yyzybb537** [comment]
3.0不再生成liblibgo.so, 你链接到so就必然是老版本。

**Comment by dearbird** [comment]
@yyzybb537 
不是吧，我用的master分支最新的代码，确实会编译出liblibgo.so
而且，不管是3.0tag，还是master分支的readme里面，都有提到动态链接，怎么会不生成动态库。

**Comment by dearbird** [comment]
我明白，我确实启用了BUILD_DYNAMIC生成了动态库。
所以libgo3.0后，推荐使用静态库？

**Comment by yyzybb537** [comment]
建议先试试使用libgo.a是否还会crash  缩小问题的检查范围

**Comment by dearbird** [comment]
尝试了静态库，不会crash。

**Comment by mlkt** [comment]
我也遇到了，确实是如果连接动态库.so版的就会崩溃
