### ISSUE TITLE
链接错误，请帮忙看按下~

### ISSUE THREAD

**Issue by marcct** [yyzybb537/libgo#108]
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1229: undefined reference to `__readv'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1230: undefined reference to `__recv'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1231: undefined reference to `__recvfrom'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1232: undefined reference to `__recvmsg'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1234: undefined reference to `__writev'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1236: undefined reference to `__sendto'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1237: undefined reference to `__sendmsg'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1238: undefined reference to `__libc_accept'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1239: undefined reference to `__libc_poll'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1241: undefined reference to `__sleep'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1246: undefined reference to `__ioctl'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1247: undefined reference to `__getsockopt'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1248: undefined reference to `__setsockopt'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1249: undefined reference to `__dup'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1251: undefined reference to `__dup3'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1252: undefined reference to `__new_fclose'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1253: undefined reference to `__gethostbyname_r'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1254: undefined reference to `__gethostbyname2_r'
/home/lib/libgo-2.9-stable/libgo/linux/linux_glibc_hook.cpp:1255: undefined reference to `__gethostbyaddr_r'

**Comment by yyzybb537** [comment]
如果要静态链接... 你的系统中必须安装gcc静态库 (libc.a)
ubuntu系的会自动给你装,  centos系的要手动装

**Comment by marcct** [comment]
好的，我试一下~另外这个问题在2.9中有，3.0中就没有了，是说3.0不需要安装吗？
