### ISSUE TITLE
libgo能绑定到csharp语言吗？

### ISSUE THREAD

**Issue by Kiddinglife** [yyzybb537/libgo#109]

**Comment by egmkang** [comment]
C#语言不是自带async/await么, 而且你想用就用, 不想用可以同步调用, 这么灵活的

**Comment by Kiddinglife** [comment]
??

On Fri, 14 Dec 2018 at 4:02 pm, egmkang wang <notifications@github.com> wrote:

C#??????async/await?, ???????, ?????????, ?????

?
