### ISSUE TITLE
sample8_multithread 并没有表现出多线程的性能

### ISSUE THREAD

**Issue by zhangzhiming865** [yyzybb537/libgo#114]
请问这个是什么原因呢？

**Comment by yyzybb537** [comment]
首先确认一下你的测试机是不是多核的

**Comment by zhangzhiming865** [comment]
[root@node3-10gtest build]# ./sample8_multithread.t
for-loop, cost 8681ms
go with coroutine, cost 8077ms
result zero:0
[root@node3-10gtest build]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
Stepping:              4
CPU MHz:               2600.147
BogoMIPS:              5199.28
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
You have mail in /var/spool/mail/root
[root@node3-10gtest build]#

**Comment by zhangzhiming865** [comment]
我把循环次数调长了一些。

**Comment by zhangzhiming865** [comment]
貌似可以。我们研究一下。厉害！

**Comment by yyzybb537** [comment]
更新一下代码吧。。。
