### ISSUE TITLE
libgo V2.9版本会锁在read()函数

### ISSUE THREAD

**Issue by hhq163** [yyzybb537/libgo#117]
因为项目中使用到了curl库，从V2.8升级到了V2.9版本，压力测试中出现以锁死问题，出错时所有线程都不能执行，跳到被锁死的线程，发送continue信号后可继续执行，使用GDB调试时，堆栈信息如下：
(gdb) info threads
  Id   Target Id         Frame 
  18   Thread 0x7f49752b9700 (LWP 23877) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  17   Thread 0x7f496dab8700 (LWP 23878) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  16   Thread 0x7f49662b7700 (LWP 23879) "game_logic_svr" 0x00007f497b54970d in read () from /lib64/libpthread.so.0
  15   Thread 0x7f495eab6700 (LWP 23880) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  14   Thread 0x7f49572b5700 (LWP 23881) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  13   Thread 0x7f494fab4700 (LWP 23882) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  12   Thread 0x7f49482b3700 (LWP 23883) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  11   Thread 0x7f4940ab2700 (LWP 23884) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  10   Thread 0x7f49392b1700 (LWP 23885) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  9    Thread 0x7f4931ab0700 (LWP 23886) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  8    Thread 0x7f492a2af700 (LWP 23887) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  7    Thread 0x7f4922aae700 (LWP 23888) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  6    Thread 0x7f491b2ad700 (LWP 23889) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  5    Thread 0x7f4913aac700 (LWP 23890) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  4    Thread 0x7f490c2ab700 (LWP 23891) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  3    Thread 0x7f4904aaa700 (LWP 23892) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
  2    Thread 0x7f48fadcb700 (LWP 23905) "game_logic_svr" 0x00007f497b546cf2 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
* 1    Thread 0x7f497bc33d40 (LWP 23876) "game_logic_svr" 0x00007f4978da1923 in epoll_wait () from /lib64/libc.so.6
(gdb) thread 16
[Switching to thread 16 (Thread 0x7f49662b7700 (LWP 23879))]
#0  0x00007f497b54970d in read () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f497b54970d in read () from /lib64/libpthread.so.0
#1  0x00007f497b7fc502 in read_write_mode<long (*)(int, void*, unsigned long), void*&, unsigned long&> (fd=1726, fn=0x7f497b5496e0 <read>, hook_fn_name=0x7f497b8122bb "read", event=1, timeout_so=20, buflen=524288)
    at /home/godspeed/LiveGameDistributed-Server/src/include/libgo/libgo/linux/linux_glibc_hook.cpp:284
#2  0x00007f497b7f57bc in read (fd=1726, buf=0x30a37be8, count=524288) at /home/godspeed/LiveGameDistributed-Server/src/include/libgo/libgo/linux/linux_glibc_hook.cpp:412
#3  0x000000000073ef98 in CIoHandler::RecvMsg (this=0x34b7c018) at /home/godspeed/LiveGameDistributed-Server/src/core/IoHandler.cpp:88
#4  0x00000000006a5b5f in CUser::ReadLoop (this=0x34b7c018) at /home/godspeed/LiveGameDistributed-Server/src/game_logic_svr/User.cpp:240
#5  0x00000000006253f2 in std::_Mem_fn<void (CUser::*)()>::_M_call<std::shared_ptr<CUser>&> (this=0x38edd360, __ptr=std::shared_ptr (count 4, weak 1) 0x34b7c018) at /usr/include/c++/4.8.2/functional:558
#6  0x0000000000624a1a in std::_Mem_fn<void (CUser::*)()>::operator()<std::shared_ptr<CUser>&, , void>(std::shared_ptr<CUser>&) const (this=0x38edd360, __object=std::shared_ptr (count 4, weak 1) 0x34b7c018) at /usr/include/c++/4.8.2/functional:610
#7  0x0000000000623e4a in std::_Bind<std::_Mem_fn<void (CUser::*)()> (std::shared_ptr<CUser>)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x38edd360, 
    __args=<unknown type in /home/godspeed/LiveGameDistributed-Server/bin/game_logic_svr/game_logic_svr, CU 0x0, DIE 0x6a4ab>) at /usr/include/c++/4.8.2/functional:1296
#8  0x0000000000622b18 in std::_Bind<std::_Mem_fn<void (CUser::*)()> (std::shared_ptr<CUser>)>::operator()<, void>() (this=0x38edd360) at /usr/include/c++/4.8.2/functional:1355
#9  0x0000000000621736 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (CUser::*)()> (std::shared_ptr<CUser>)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/4.8.2/functional:2071
#10 0x000000000077e81c in std::function<void ()>::operator()() const (this=0x2f3f5b30) at /usr/include/c++/4.8.2/functional:2471
#11 0x00007f497b7d2a95 in co::Task::__lambda2::operator() (__closure=0x30ab7e90) at /home/godspeed/LiveGameDistributed-Server/src/include/libgo/libgo/task.cpp:44
#12 0x00007f497b7d2b95 in co::Task::Task_CB (this=0x2f3f5700) at /home/godspeed/LiveGameDistributed-Server/src/include/libgo/libgo/task.cpp:53
#13 0x00007f497b7d304b in co::Task::__lambda3::operator() (__closure=0x1b3d4068) at /home/godspeed/LiveGameDistributed-Server/src/include/libgo/libgo/task.cpp:98
#14 0x00007f497b7d3dbc in std::_Function_handler<void(), co::Task::Task(const TaskF&, std::size_t, char const*, int)::__lambda3>::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/4.8.2/functional:2071
#15 0x000000000077e81c in std::function<void ()>::operator()() const (this=0x2f3f5af8) at /usr/include/c++/4.8.2/functional:2471
#16 0x00007f497b7d4a9c in co::Context::ucontext_func(std::function<void ()>*) (pfn=0x2f3f5af8) at /home/godspeed/LiveGameDistributed-Server/src/include/libgo/libgo/ctx_ucontext/context.h:62
#17 0x00007f4978cefd40 in ?? () from /lib64/libc.so.6
#18 0x0000000000000000 in ?? ()
(gdb) c
Continuing.

Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7f492a2af700 (LWP 23887)]
0x00007f497b5496ad in write () from /lib64/libpthread.so.0
(gdb) c
Continuing.

Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7f4904aaa700 (LWP 23892)]
0x00007f497b5496ad in write () from /lib64/libpthread.so.0

IoHandler.cpp:88行代码调用了read()：
/**
 * 接收数据包
 */
int CIoHandler::RecvMsg(){
    int iErr = IO_FAILED;
    BUFFER_t tmpBuffer;
    tmpBuffer.iSize = 0;
    Logger.Log(DEBUG, "CConn::RecvPkg() in m_iSockFd=%d\n", m_iSockFd);
RetryRead:
    int iRet = read(m_iSockFd, (char*)tmpBuffer.cBuffer + tmpBuffer.iSize, MAX_BUFFER_SIZE - tmpBuffer.iSize);
    Logger.Log(DEBUG, "CIoHandler::RecvPkg(), iRet=%d\n", iRet);
    if (iRet < 0){
        if (errno == EINTR) {//操作被中断，可以继续读取
//            Logger.Log(INFO, "222trigger EINTR. socket=%d\n", m_iSockFd);
            goto RetryRead;
        }
        if(EAGAIN == errno){//现在没有数据，过会再试
            iErr = IO_EAGAIN;
//            Logger.Log(INFO, "222trigger EAGAIN. socket=%d\n", m_iSockFd);
            goto RetryRead;
        }
        Logger.Log(ERROR, "33trigger EINTR. socket=%d, read() iRet=%d, errno=%d, strerror=%s\n", m_iSockFd, iRet, (int)errno, strerror(errno));
        iErr = IO_CLOSE;

    }else if(0 == iRet){//连接关闭
        Logger.Log(ERROR, "socket:%d peer shutdown", m_iSockFd);
        iErr = IO_CLOSE;
    }else{
        iErr = IO_SUCCESS;
        tmpBuffer.iSize += iRet;
        m_activeTime = time(NULL);
    }

    m_inBuf->Write(tmpBuffer.cBuffer, tmpBuffer.iSize);

    return iErr;
}

各位libgo开发人员，看下是什么原因？

**Comment by hhq163** [comment]
我把调用CURL请求的业务注释，程序一切正常，CRUL请求连接超时30秒，读取数据超时时间60秒，是因为超时时间设置太长未得到响应的原因？

**Comment by yyzybb537** [comment]
建议试试3.0

**Comment by yyzybb537** [comment]
建议试试master分支上的最新版本
