### ISSUE TITLE
如何跑满cpu

### ISSUE THREAD

**Issue by rileylu** [yyzybb537/libgo#121]
co_sched.Start(0) 无法跑满cpu。

**Comment by rileylu** [comment]
我写了个简单的server， 用wrk测试。最高都是25%。而且wrk有很多read error。是这个工具不兼容的问题吗

**Comment by yyzybb537** [comment]
不存在工具不兼容的问题，可能是server写的有问题

**Comment by rileylu** [comment]
好的。另外有个问题，我用cmake编译的时候好像没有依赖boost，我看到网上说打开boost 的context再linux下的性能是最佳的。请问下如何打开那个boost context依赖

**Comment by yyzybb537** [comment]
已经自动集成了boost.context在里面
