### ISSUE TITLE
关于kqueue

### ISSUE THREAD

**Issue by heiher** [yyzybb537/libgo#122]
epoll是使用ET模式，kqueue用LT模式不会在某些情况下使kevent持续返回，但又不能处理这个event吗？

另外，kqueue实现中kevent(set)和kevent(wait)是有机会合并成一次系统调用的。

**Comment by yyzybb537** [comment]
kqueue在使用时模拟了ET模式

kevent确实可以优化，不过我认为这一点点性能差异微不足道
