### ISSUE TITLE
Processer::Process() 调用runningTask_->SwapIn();之后，什么情况下，task出来的状态是Runable

### ISSUE THREAD

**Issue by magicsupery** [yyzybb537/libgo#127]

**Comment by magicsupery** [comment]
#include "../../libgo/coroutine.h"


void block()
{
    DebugPrint(co::dbg_task, "block function.");
	sleep(10);
}


void runable()
{
  
}



void done()
{
    DebugPrint(co::dbg_task, "done function.");
}

void foo()
{
	go block;
    go runable;
	go done;
	
}

int main()
{
	go foo;
	co_sched.Start();
}


能否给一个runable的实现例子？

**Comment by yyzybb537** [comment]
用co_yield;出来就是runnable

**Comment by magicsupery** [comment]
> 用co_yield;出来就是runnable

多谢指点
