### ISSUE TITLE
请问下有计划hook pthread_cond_wait函数么？

### ISSUE THREAD

**Issue by wugang33** [yyzybb537/libgo#129]
您好， 我有一个三方库，内部使用了独立的线程，三方库的内部使用了pthread_cond_wait等待网络rpc请求的完成。 我希望能够使用libgo来和这个三方库交互。 需要hook pthread_cond_wait. 请问下这个从原理上能够做到么？
以及您是否有这方面的计划呢？

**Comment by yyzybb537** [comment]
可以用协程池模式来解决，看readme

**Comment by wugang33** [comment]
好的。看到了。 非常感谢。
