### ISSUE TITLE
accept 异常阻塞问题

### ISSUE THREAD

**Issue by dearbird** [yyzybb537/libgo#132]
libgo 版本 2.9 stable

程序中listen 2个 tcp 端口，一个正常，另一个accept就会阻塞住。
查看堆栈，阻塞在系统调用
#0  0x00007ff145cce71d in accept () from /lib64/libpthread.so.0

1. 该程序跑在另一台机器，均不会阻塞。
2. 该程序之前已经跑了几个月了，均未发现有阻塞。
3. 在该机器上，今天出现问题后，每次执行均会阻塞
4. 重启机器后，依然会阻塞。

目前毫无头绪，请问是否有相关经验可以分享？

**Comment by runner365** [comment]
类似问题，同问，关注

**Comment by yyzybb537** [comment]
有可以复现问题的代码吗？

**Comment by dearbird** [comment]
已切换为master版本，暂时无法复现。
