### ISSUE TITLE
libgo2.0设计上的一些讨论

### ISSUE THREAD

**Issue by bigbao9494** [yyzybb537/libgo#156]
@yyzybb537
先说windows吧，我在这个平台上看了一下代码：
因为libgo的网络处理是hook系统IO调用来实现阻塞socket到协程的转换，把阻塞socket转换成协程sleep实现的，所以它必须要保存sleep队列中的task能够得到充分地执行，就是把同步IO通过协程sleep方式变成异步(这样才不会阻塞物理线程)，这样其实就会在线程中不停地查询sleep队列中的所有socket，通过不停地调用select来查询而且是每个socket都会不停地去查询，这样效率是比较低的。如果设计不用考虑第3方库的话就可以不用hook系统调用而使用库中自己的API比如:go_send,go_recv，因为这样做可以不用考虑高频率地处理sleep中的socket，所有的socket都放到同一个select/io_wait中去查询是否可操作，不用频繁调用select/io_wait(这里超时时间会决定sleep和timer的精度)，如果这只是一个网络库最大的负载还是处理IO数据，高效的IO会是库的重点

windows平台网络IO处理过程，协程中调用系统调用send，因为hook了一些系统调用所以会转到hook_send  -->  write_mode_hook: SetNonblocking(s, true)把socket变成非阻塞，R ret = fn(s, std::forward<Args>(args)...)先调用原始函数就是系统的send尝试发送数据如果成功了把socket还原成原来的非阻塞再返回，如果send失败表示可能需要等待执行select(1, NULL, &wfds, NULL, timeout ? &tm : NULL)  -->  hook_select：会循环调用safe_select(nfds, readfds, writefds, exceptfds)系统的select判断是否socket可以发送数据，如果socket不可写则调用g_Scheduler.SleepSwitch(delta_time)使用协程的sleep来切换协程，每次协程sleep唤醒后会检查是否超时如果超时则退出循环返回0，如果socket可写则返回的是系统select的值(>0)，返回到wirte_mode_hook后会执行ret = fn(s, std::forward<Args>(args)...);系统send完成最终数据发送。

**Comment by bigbao9494** [comment]
如果第1，2两点是设计目的，那么在3.0中是如何设计的？
还有就是有一种需求：项目中不会用到第3方库
在3.0中是否有考虑或者说是怎样处理这种情况 ？

**Comment by bigbao9494** [comment]
如果第1，2两点是设计目的，那么在3.0中是如何设计的？
还有就是有一种需求：项目中不会用到第3方库
在3.0中是否有考虑或者说是怎样处理这种情况 ？
为什么提这个，就是因为实际这种需求确实有不少，感觉2.0中
的设计非常复杂而且可能影响效率和内存的使用，如果不考虑1，2
两点，会让设计变得简单且高效。

**Comment by yyzybb537** [comment]
首先，上面关于libgo2.0在windows上的实现的说法，我是认同的。
2.0时期的设计思想是：Linux是主要用户，Windows上的兼容只是为了满足“windows开发、linux部署”的用户需求。因为这样的设计思想，加上iocp的preactor模型实现hook的时候的各种问题，采用了非常简单的轮询实现。
3.0时期的设计思想有所变化，希望能够满足更多平台的用户(linux, windows, mac等), 所以windows上的hook实现改成了多个socket分桶聚合到一起select的模式 (可以参照asio的select_reactor).

**Comment by bigbao9494** [comment]
> 首先，上面关于libgo2.0在windows上的实现的说法，我是认同的。
> 2.0时期的设计思想是：Linux是主要用户，Windows上的兼容只是为了满足“windows开发、linux部署”的用户需求。因为这样的设计思想，加上iocp的preactor模型实现hook的时候的各种问题，采用了非常简单的轮询实现。
> 3.0时期的设计思想有所变化，希望能够满足更多平台的用户(linux, windows, mac等), 所以windows上的hook实现改成了多个socket分桶聚合到一起select的模式 (可以参照asio的select_reactor).

关于LINUX下的问题还望解答一下，

**Comment by bigbao9494** [comment]
@yyzybb537 3.0有没有设计文档之类的，我也想为LIBGO尽点绵薄之力，由于工作的原因无法花太多的精力，所以想尽快地进入3.0。我之前在2.0上修改的一些东西可以用到3.0上，比如用汇编实现的协程切换（独立于第3方模块和代码），一个汇编文件不同平台使用不同代码。

**Comment by yyzybb537** [comment]
2.0时期，对网络io的设计思想是：用hook劫持进程中的全部网络IO，并且自信可以做的足够满足需求，也因此衍生了libgonet这个同步io+libgo实现的网络库，并且在libgonet的基础上重构了我们的单线程微服务框架。libgo2.6这个版本也确实支撑住了我们千万级PCU的推送系统后台，也在2.x版本末期写了一篇<<Why cpp coroutine? Why libgo?>>的wiki，可以说是总结了协程库使用过程中的一些思考和演进过程。

但是，经过一段时间的团队自用和用户反馈，我在其中发现了一些问题：

1. HOOK问题：虽然hook了fcntl等接口，让被改成非阻塞模式的socket在用户看来依然保持阻塞socket的样子，并且记录了epoll的可读可写事件；这两个设计目前看来都还运行良好，但很难排除一些小众库做出出乎意料的骚操作，这是一个从设计上无法证明他没bug的事情。如果不改为非阻塞模式，实现上更加安全，但性能方面又会受损一点。

2. 线程问题：2.0支持多线程调度，但是没有提供隔离机制，C++er却很喜欢per xxx per thread（这样可以减少线程间竞争）。
对于线程的使用也过于保守了，epoll集成到调度线程中并不是一个最好的设计，既有带来不必要的设计复杂性，还会在运行时和协程调度相互干扰。
libgo2.x的worksteal设计方式也不是很理想，对协程切换速度也有比较深的影响，每次切换大概需要100ns左右。

3.历史包袱问题：很多项目当前都是基于一套异步网络框架搭建起来的，比如asio\libuv\libevent等，突然某一天项目中要引入mysqlclient这类半双工协议的同步组件时，就觉得很难受，希望能够引入libgo来简单的解决这个问题。

4.还有一些问题暂时想不起来了...

鉴于以上的一些问题，libgo3.0做了一次大调整，首先是设计思想上扭转：

* 积极利用多线程解决一些设计上的问题，但对用户透明，用户依然可以编写单线程逻辑的程序。
* 不再排斥异步网络库，寻求结合使用的方案，让有历史包袱的用户可以零成本引入libgo。
* 提供线程隔离机制（用户可以创建多个Scheduler）

**Comment by yyzybb537** [comment]
其次是实现选型上的变化：

* 协程上下文切换不再提供多套给用户选择，直接提供最佳选择，unix系列系统上直接抽取boost.context 1.60的汇编文件(系统自适应的，不需要用户安装boost)，windows上使用fiber。
* 重新设计架构、分层解耦，调度就只做调度的事情，提供“休眠 & 唤醒”原语给上层使用，网络io的hook、mutex、channel、timer等等功能都是基于这两个原语实现的。
架构分层后，每个模块都可以单独去优化、开发，便于社区协作开发。
* 重新设计调度器，使用一个dispatch线程来定时扫描，这样有了更多的发挥空间。
即可以均衡调度线程的负载。
同时可以检测到被协程长期阻塞的调度线程（比如while(true);），将这种被“头部阻塞”的调度线程中的其他协程任务全部steal到其他线程。
还可以动态增加调度线程，以应对调度线程被阻塞在io上的情况。
由于调度线程的逻辑变轻，更容易优化切换速度。（3.0的每次切换大概需要25ns）
* HOOK部分使用安全性更好、但是性能稍微受损的方式来实现。比较care网络性能的场景，可以和fast_asio(一个对asio做了扩展的库)搭配使用(参加: test/asio)，也可以搭配其他任意高性能的网络库。

**Comment by bigbao9494** [comment]
@yyzybb537
1、因为2.0中可能有下面这个问题，我没有看3.0代码，不知道3.0是否也存在，所以向你确认一下：
IoWait::GetEpollFd的值是每个线程都不同的因为每个线程都有独立的epoll_wait，这样epoll_fd_的值会由第一次调用FileDescriptorCtx::GetEpollFd函数的那个task所在的线程决定，以后每次对这个fd的poll操作都会到同一个epoll_fd_上去就是会由同一个线程的IoWait::WaitLoop来唤醒，因为FdManager::get中生成fd对应的FileDescriptorCtx后存放到fd_deque_中是不会删除它的，IoWait::WaitLoop中也不会去重新初始化FileDescriptorCtx::epoll_fd_，这样会带来问题就是有可能一个线程的epoll_wait上有很多个fd在wait而其它线程上可能没有fd，造成epoll的极不均衡，stealwork算法也无法均衡epoll_wait只能均衡task，如果只考虑一个fd只能存在于一个task中使用就可以让epoll_wait跟随着task来变动，这样才能做到真正的线程负载均衡

2、3.0有没有设计文档之类的，我也想为LIBGO尽点绵薄之力，由于工作的原因无法花太多的精力，所以想尽快地进入3.0。我之前在2.0上修改的一些东西可以用到3.0上，比如用汇编实现的协程切换等（独立于第3方模块和代码），一个汇编文件不同平台使用不同代码，关于这点我觉得是可以独立而不使用BOOST，更简洁易用效率也不输，而且实现和维护不麻烦，现在平台常用的就是LINUX/WINDOWS/MAC，CPU常用的就是X64/86/ARM64/MIPS，LINUX下就是AT&T汇编语法WNDOWS下就是INTEL语法，基本做到这几个主流的平台应该就差不多了。如果可行的话先把2.0上实现的这块发给你审核一下，看是否可以替换掉BOOST库中的栈切换这块。

**Comment by yyzybb537** [comment]
1.在3.0中，fd是根据fd的整数值轮询使用epoll线程的，数量方面基本上均衡。
2.新版对boost.context 1.60是采取编译前自动抽源码的方式，对用户透明的，从需求上看是满足的。从稳定性上看，boost.context被测试的次数还是远多于自己实现的，这也是我没有自己动手写汇编的重要原因之一。

**Comment by bigbao9494** [comment]
> 1.在3.0中，fd是根据fd的整数值轮询使用epoll线程的，数量方面基本上均衡。
> 2.新版对boost.context 1.60是采取编译前自动抽源码的方式，对用户透明的，从需求上看是满足的。从稳定性上看，boost.context被测试的次数还是远多于自己实现的，这也是我没有自己动手写汇编的重要原因之一。

@yyzybb537 有没有LIBGO讨论群之类的呢？

**Comment by yyzybb537** [comment]
296561497
