### ISSUE TITLE
msgchannel的timedpop偶现异常返回

### ISSUE THREAD

**Issue by dearbird** [yyzybb537/libgo#158]
有一定概率，当timedpop返回true时，消息并没有返回。

@yyzybb537 
该api的定义是否如此？我能依赖返回值来确认一定有一条消息被读出吗？

**Comment by yyzybb537** [comment]
不符合预期，有可能是存在bug，可以提供复现代码吗

**Comment by bigbao9494** [comment]
> 不符合预期，有可能是存在bug，可以提供复现代码吗

@yyzybb537 
看一下这个问题呗：https://github.com/yyzybb537/libgo/issues/157

**Comment by dearbird** [comment]
最新版本已运行一段时间了，没有出现。
