### ISSUE TITLE
tutorial中测试代码编译后运行显示:"Hook syscall failed. Please don't remove libc.a when static-link"

### ISSUE THREAD

**Issue by lwjimmy** [yyzybb537/libgo#16]
测试代码编译后运行失败：Hook syscall failed. Please don't remove libc.a when static-link.
按照说明进行编译安装
系统：centos 5.8
gcc: gcc 4.8.2

**Comment by lwjimmy** [comment]
通过代码发现是 dup3 引出失败

**Comment by yyzybb537** [comment]
centos 5.8
这个OS版本太老  还没有dup3这个syscall吧.

**Comment by yyzybb537** [comment]
提交了一个兼容的版本, 你拉取一下最新代码试试
