### ISSUE TITLE
线程安全问题

### ISSUE THREAD

**Issue by siemonchan** [yyzybb537/libgo#167]
求问如果用libgo调度器的多线程start，但是协程内部并不是线程安全的，会产生问题吗？

**Comment by yyzybb537** [comment]
协程同一时刻只会被一个线程run

**Comment by ylovecj** [comment]
> 协程同一时刻只会被一个线程run

1、如果协程都是在一个线程下运行，那协程处理中的共享数据就不会有线程安全问题，但是协程可能会被多个线程调度的话， 那这些资源的使用是不是就要加锁保护了?

**Comment by siemonchan** [comment]
多个线程公用的部分是要加锁的，不过这个问题仅在多线程下也是要考虑的
