### ISSUE TITLE
协程coredump问题

### ISSUE THREAD

**Issue by hbt19860104** [yyzybb537/libgo#168]
![image](https://user-images.githubusercontent.com/5079173/56089936-111e0f00-5ecd-11e9-8310-8b6c73e4e542.png)
一个很简单的测试程序，如果在协程里有sleep，就不会coredump，如果没有，运行时在staticInitialize函数里调用initHook时发生coredump。堆栈信息如下：
![image](https://user-images.githubusercontent.com/5079173/56089963-60fcd600-5ecd-11e9-8171-b0b6ed099d31.png)
如果注释掉其中任一个sleep，就没问题。
请教大神这是什么原因？
![image](https://user-images.githubusercontent.com/5079173/56089977-95709200-5ecd-11e9-99c5-7258f0ce9f8c.png)

**Comment by hbt19860104** [comment]
![image](https://user-images.githubusercontent.com/5079173/56090003-4b3be080-5ece-11e9-82e0-15553d148f4d.png)

**Comment by dddlee88** [comment]
一样能重现这个问题，发现只要代码里面有sleep就不会死机，并非是协程里面要有sleep。
怀疑是hook的时候有点异常。

**Comment by dddlee88** [comment]
> 一样能重现这个问题，发现只要代码里面有sleep就不会死机，并非是协程里面要有sleep。
> 怀疑是hook的时候有点异常。

取了最新代码测试 已经无死机了。

**Comment by hbt19860104** [comment]
谢谢大神
