### ISSUE TITLE
 Scheduler::CreateTask中TaskRefAffinity和TaskRefLocation做什么用的？

### ISSUE THREAD

**Issue by bigbao9494** [yyzybb537/libgo#169]
下面这两行没有看懂它们的作用是什么？
    TaskRefAffinity(tk) = opt.affinity_;
    TaskRefLocation(tk).Init(opt.file_, opt.lineno_);

**Comment by yyzybb537** [comment]
上面的优先级  已经废弃了
下面的是__FILE__  __LINE__   打印日志用的
