### ISSUE TITLE
windows编译失败

### ISSUE THREAD

**Issue by lipeilei** [yyzybb537/libgo#172]
这样生成的vs2017的工程目录：
cmake .. -G"Visual Studio 15 2017 Win64" "E:\\Git\\third\\libgo" -DBOOST_ROOT="E:\\Git\\third\\boost"

vs2017编译的时候报错
![图片](https://user-images.githubusercontent.com/13651773/56709443-f14fdc00-6753-11e9-88b2-68f5b53df330.png)

**Comment by lipeilei** [comment]
git config --global core.autocrlf true  就可以了

**Comment by rooong** [comment]
对的，未做git config --global core.autocrlf true 设置时，checkout出来的代码行尾是LR，会报这个问题
