### ISSUE TITLE
连接池CheckAlive问题

### ISSUE THREAD

**Issue by hbt19860104** [yyzybb537/libgo#173]
你好！
![image](https://user-images.githubusercontent.com/5079173/56873218-66c4f080-6a63-11e9-8d38-5e5e87113f36.png)
这边是不是应该--count_啊？
我现在出现这种情况 ：
连接池取不到连接，去重新连接时发现最大连接数超过限制
![image](https://user-images.githubusercontent.com/5079173/56873229-780dfd00-6a63-11e9-80c8-60f7446c9fd3.png)

**Comment by yyzybb537** [comment]
嗯 这一块确实有问题，已经修复了，你拉取最新代码试试吧
