### ISSUE TITLE
xp系统无法运行

### ISSUE THREAD

**Issue by gswgit** [yyzybb537/libgo#185]
我在win10下把库编译完毕后，然后写了一个静态程序，在win10  win7下面都可以正常运行，但是在xp下就报错，不是有效的win32应用程序

**Comment by gswgit** [comment]
请问该怎么解决此问题

**Comment by yyzybb537** [comment]
我记得好像是vs的设置上要设置成xp兼容

**Comment by gswgit** [comment]
好的，我先设置一下看看
