### ISSUE TITLE
概率性 crash

### ISSUE THREAD

**Issue by dearbird** [yyzybb537/libgo#217]
![image](https://user-images.githubusercontent.com/1276668/75326897-6d580a80-58b6-11ea-95fc-c20a8a5847d8.png)

无直接创建定时器，应该是sleep，TimedPop 之类的间接调用产生的定时器。

**Comment by dearbird** [comment]
![image](https://user-images.githubusercontent.com/1276668/77053448-55812b80-6a09-11ea-98b6-94c0d4b68119.png)
这个就更奇怪了，processer_的地址指针异常了

这两个问题都是长时间运行后出现的

**Comment by yyzybb537** [comment]
踩内存了吧？

**Comment by dearbird** [comment]
我也怀疑应该是哪里内存越界了，但是用valgrind没跑出来，不知道是不是valgrind对协程支持不好。

**Comment by yyzybb537** [comment]
有用户反馈过vld对协程无用的，如果是可复现的，可以用gdb的数据断点来调试

**Comment by dearbird** [comment]
复现概率比较低，近一个月，60台机器，只出现了4次。

**Comment by yyzybb537** [comment]
emmmmmm  那这个... 真是个C系语言通用的难题了

**Comment by yyzybb537** [comment]
我的经验方法是：“让每个微服务进程的代码量足够少，少到不那么难查问题”

**Comment by dearbird** [comment]
目前还不算复杂，代码量不到1w行，而且使用协程后，逻辑实现起来都比较直白。
只能再观察下是不是有什么蛛丝马迹了。
另外 #212 应该是库的问题，这个可以简单重现。

**Comment by dearbird** [comment]
受攻击收到非法报文时，处理不当导致内存越界。
