### ISSUE TITLE
Version 3.1 cannot build on Windows

### ISSUE THREAD

**Issue by NancyLi1013** [yyzybb537/libgo#223]
The version 2.8 is broken in vcpkg, since there is no `execution_context.hpp` in `boost `1.72.

I try to build the latest version 3.1 via vcpkg, but it posted the error:

`ninja: error: unknown target 'install'`

I also checked CMakeLists, there is no any target to be installed on Windows.
https://github.com/yyzybb537/libgo/blob/v3.1-stable/CMakeLists.txt#L153-L155

Can anyone tell me the current status for `libgo `on Windows?

**Comment by zh1an** [comment]
> The version 2.8 is broken in vcpkg, since there is no `execution_context.hpp` in `boost `1.72.
> 
> I try to build the latest version 3.1 via vcpkg, but it posted the error:
> 
> `ninja: error: unknown target 'install'`
> 
> I also checked CMakeLists, there is no any target to be installed on Windows.
> https://github.com/yyzybb537/libgo/blob/v3.1-stable/CMakeLists.txt#L153-L155
> 
> Can anyone tell me the current status for `libgo `on Windows?

Hi, @NancyLi1013 
Please try `vcpkg_build_cmake`.

**Comment by NancyLi1013** [comment]
@zh1an 

Thanks for your info. I  will try it agian.

**Comment by NancyLi1013** [comment]
Using `vcpkg_build_cmake` to build on Windows and it can work now.

Thanks again for your help @zh1an .
