### ISSUE TITLE
为什么当设定sched->Start(8);程序死亡， sched->Start()可以正常工作

### ISSUE THREAD

**Issue by nqf** [yyzybb537/libgo#229]
co::Scheduler* sched = co::Scheduler::Create();

		std::vector<std::string> vec;

		go co_scheduler(sched)[&]() {
			while (true) {
				if (!vec.empty()) {
					for (auto& v : vec)
						std::cout << v << std::endl;
					vec.clear();
				}
				co_yield;
			}
		};
		go co_scheduler(sched)[&]() {
			int i = 0;
			while (true) {
				vec.emplace_back("hello" + std::to_string(i++));
				co_yield;
			}
		};
		sched->Start(8);

**Comment by yyzybb537** [comment]
这显然是个非线程安全的代码，start8表示有8个调度线程，所以会crash
