### ISSUE TITLE
向协程池添加调用函数时，如何将函数实参传进去

### ISSUE THREAD

**Issue by lhcpicture** [yyzybb537/libgo#244]
// 1.以回调的方式投递任务 (适用于异步回调模型的项目)
    pPool->Post(&foo, &done);
假设foo需要参数，应该如何传入呢

**Comment by hnwyllmm** [comment]
foo是个对象吗？如果是的话，传一个lamda表达式进去，不是的话把参数和函数封装一下，创建个对象传进去

**Comment by lhcpicture** [comment]
> foo是个对象吗？如果是的话，传一个lamda表达式进去，不是的话把参数和函数封装一下，创建个对象传进去

可以了，感谢
