### ISSUE TITLE
channel唤醒延时

### ISSUE THREAD

**Issue by smithnote** [yyzybb537/libgo#277]
* 系统: centos-7 x86_64
* gcc: 4.8.5
* libgo版本：3.1-stable
* 场景：我创建了100个协程，每个协程中都读取channel（被挂起），之后在一个原生线程中写这100个channel，发现有一定概率的携程被延时了100m后才被唤醒，是需要设置什么参数吗，还是bug？

**Comment by yyzybb537** [comment]
master分支的最新代码已修复这个bug
