### ISSUE TITLE
[交流交流] 阿里最新开源的协程库和I/O库

### ISSUE THREAD

**Issue by beef9999** [yyzybb537/libgo#279]
https://github.com/alibaba/PhotonLibOS
支持io_uring作为事件引擎和I/O引擎哦

**Comment by jiangdongzi** [comment]
> https://github.com/alibaba/PhotonLibOS 支持io_uring作为事件引擎和I/O引擎哦

有对比过性能么 最近在选协程库

**Comment by beef9999** [comment]
@jiangdongzi 首页就有性能对比啊

**Comment by zhengshuxin** [comment]
> @jiangdongzi 首页就有性能对比啊
我看了一下，并尝试编译使用，整体感觉成熟度还差一些，例子都无法编译使用，而且还依赖一个庞大的 boost 库，希望能在实用性多完善完善。

**Comment by beef9999** [comment]
- 不会编译不过的，可能是你的环境太老。
- 可以看一下About Photon那部分的介绍，这个是production ready的库
- boost现在用了beast模块，为了http解析，很快也会被去掉

**Comment by zhengshuxin** [comment]
我用的是centos8，acl fiber 是甚至可以在cs5.4上编译，另外，希望多提供一些例子，因为上面只有几个例子，编译了几个，都运行不起来。

**Comment by beef9999** [comment]
只是运行不起来吗？那是因为代码默认开了io_uring，如果内核不支持io_uring要调整代码换成epoll，这个在注释里面写了一大段

**Comment by zhengshuxin** [comment]
是的，换成epoll也跑不起来，我把simple例子改了一下。要不还是去你们那儿讨论吧。

**Comment by zhengshuxin** [comment]
另外，性能对比也只是一方面影响因素，更为重要的是其基础设施的完善性，以及实践中的应用规模是否足够大、应用场景是否比较多。目前根据我的了解象 libco, libgo (go就不必说了) 都在较大规模机器上使用过，而 acl fiber 我们也在上万台服务器上实践过，而且是比较复杂的应用场景，目前在某项关键性业务上已经在逐步替换Nginx，单个POD可以支撑几十万个并发连接。

**Comment by zhengshuxin** [comment]
没错，我也是这个意思，本来也想这样说，另外，对于这种跑别人项目里推广宣传自己那个不太成熟项目的做法表示反感。一个好的开源项目得要看应用场景、使用规模等方面，而不是一味地为了宣传自己去说性能。后来居然还在libco里看到该项目的宣传，所以就懒得再去评判了，至少不应该去别人的项目宣传自己的项目。

**Comment by paradiseforgithub** [comment]
已收到您的邮件,如有问题会尽快给您回复.
