### ISSUE TITLE
于大大，Block相关的代码比较难懂。。。希望有个设计文档

### ISSUE THREAD

**Issue by kkHAIKE** [yyzybb537/libgo#3]
Scheduler中的Block处理和BlockObject部分

**Comment by yyzybb537** [comment]
嗯  文档方面我会趁着春节假期慢慢完善，在此可以先说一下block

block是阻塞协程的意思，阻塞式的网络IO会产生这样的效果，co_mutex、channel也会产生这样的效果。
前者可以用OS提供的epoll来保存待唤醒协程，后者就只能通过blockobject来保存了。
