### ISSUE TITLE
BlockObject在协程外 带超时的等待 的一点疑问

### ISSUE THREAD

**Issue by jinxianda** [yyzybb537/libgo#37]
bool BlockObject::CoBlockWaitTimed(MininumTimeDurationType timeo)
{
    auto begin = std::chrono::steady_clock::now();
    if (!g_Scheduler.IsCoroutine()) {
        while (!TryBlockWait() &&
				std::chrono::duration_cast<MininumTimeDurationType>
                (std::chrono::steady_clock::now() - begin) < timeo)
            usleep(10 * 1000);
        return false;
    }
......
在协程外不是必然返回false?

**Comment by yyzybb537** [comment]
不是

**Comment by jinxianda** [comment]
可是这样的话，如果在协程外执行co_chan<T>的TimedPop成员函数不管是不是真的超时都返回false啊？

**Comment by moying050** [comment]
的确，在协程外等待都是返回false

**Comment by yyzybb537** [comment]
TryBlockWait()执行成功时, 会返回true

**Comment by jinxianda** [comment]
@moying050 是的，稍微修改一下就行，把超时判断挪出来，分别返回true,false就行，只能自己重新编译一下了

**Comment by yyzybb537** [comment]
已经修复
