### ISSUE TITLE
io_wait中的epoll_create_lock_作用？

### ISSUE THREAD

**Issue by txsniper** [yyzybb537/libgo#41]
epoll_owner_pid和epoll_fd都是thread_local的，这意味着每个调度线程在创建epoll fd时并不会相互冲突，那么epoll_create_lock的作用在什么地方？

**Comment by yyzybb537** [comment]
用于防止重复创建

**Comment by txsniper** [comment]
@yyzybb537 ，什么情况下会出现重复创建？

**Comment by yyzybb537** [comment]
最早是多线程共享epoll的，需要防止重复创建，现在确实不需要这个lock了
