### ISSUE TITLE
协程栈空间分配失败导致段错误

### ISSUE THREAD

**Issue by weingithub** [yyzybb537/libgo#42]
在使用ctx_ucontext/context.h的Context类构造代码：
`            if (-1 == getcontext(&ctx_)) {
                ThrowError(eCoErrorCode::ec_makecontext_failed);
                return ;
            }

            stack_ = (char*)StackAllocator::get_malloc_fn()(stack_size_);
            DebugPrint(dbg_task, "valloc stack. size=%u `ptr=%p",`
                    stack_size_, stack_);

            ctx_.uc_stack.ss_sp = stack_;
            ctx_.uc_stack.ss_size = stack_size_;
            ctx_.uc_link = NULL;

            makecontext(&ctx_, (void(*)(void))&ucontext_func, 1, &fn_);
`
中，当StackAllocator分配空间失败，此时stack_为NULL，会导致makecontext时出现段错误。
我的机器内存是1G，运行，test/golang/下的libgo_test，遇到
` go []{ test_switch(10000); };`
执行这个协程内容时，就会出段错误，最终发现是内存不足。

**Comment by yyzybb537** [comment]
内存不足问题并未处理
libgo是为linux server设计的，server端的内存通常都很充足

**Comment by moying050** [comment]
分配失败直接core掉是不是好一点
