### ISSUE TITLE
可以维护一下Mac分支吗？

### ISSUE THREAD

**Issue by zouquan741** [yyzybb537/libgo#43]
cmake .. -DENABLE_BOOST_CONTEXT=ON -DBOOST_ROOT="/opt/local" -DDISABLE_HOOK=ON

之后make各种报错：
use of undeclared identifier 'getpagesize'（头文件没引）
-Werror（有未使用的函数也报错）
即使正确设置了BOOST_ROOT，链接的时候也找不到boost库

花了一个多小时才在xcode里编过了。。。

**Comment by yyzybb537** [comment]
欢迎提交mac分支的PullRequest

**Comment by yyzybb537** [comment]
3.x已兼容mac
