### ISSUE TITLE
请问新的线程是内部自动启动的吗？

### ISSUE THREAD

**Issue by mlkt** [yyzybb537/libgo#47]
新的线程是库内部根据需要自己启动的吗？还是需要调用方自己启动若干线程，然后再在每个线程里调用Run？

另外thread_pool.cpp里这段有没有潜在的内存泄漏？
如果协程里有异常抛出，`delete elem;` 这句是不是会被跳过？
还是异常抛到此处之前会被吃掉？用unique_ptr包住会不会好一点？

```
void ThreadPool::RunLoop()
{
    assert_std_thread_lib();
    for (;;)
    {
        TPElemBase *elem = get();
        if (!elem) continue;
        elem->Do();
        delete elem;
    }
}
```

**Comment by yyzybb537** [comment]
用unique_ptr确实会更好一些，可以提个pr
