### ISSUE TITLE
存在对智能指针并发读写的bug

### ISSUE THREAD

**Issue by moying050** [yyzybb537/libgo#48]
`

bool BlockObject::Wakeup()
{
...
    tk->block_ = nullptr;
    if (tk->block_timer_) { // block cancel timer必须在lock之外, 因为里面会lock
        if (g_Scheduler.BlockCancelTimer(tk->block_timer_))
            tk->DecrementRef();
        tk->block_timer_.reset();
    }
...
}
void BlockObject::CancelWait(Task* tk, uint32_t block_sequence, bool in_timer)
{
...
    tk->block_ = nullptr;
    if (!in_timer && tk->block_timer_) { // block cancel timer必须在lock之外, 因为里面会lock
        g_Scheduler.BlockCancelTimer(tk->block_timer_);
        tk->block_timer_.reset();
    }
...
}

`
上述代码可能不是在同一个线程中执行的，在开启了偷协程的机制时，此时有场景存在并发，导致block_timer_指针指向内存释放后还被访问

**Comment by yyzybb537** [comment]
这俩接口都是加了锁的

**Comment by moying050** [comment]
`

bool BlockObject::Wakeup()
{
    **std::unique_lock<LFLock> lock(lock_);**
......
    **lock.unlock();**
    tk->block_ = nullptr;
    if (tk->block_timer_) { // block cancel timer必须在lock之外, 因为里面会lock
        if (g_Scheduler.BlockCancelTimer(tk->block_timer_))
            tk->DecrementRef();
       tk->block_timer_.reset();
}

`
lock_在执行这段代码前已经释放了，CancelWait中也是

**Comment by yyzybb537** [comment]
这两段代码不会被并行，因为一个协程在同一时间只会被一个线程处理

**Comment by moying050** [comment]
0. 前提是有多个线程执行Run进行协程调度；
1. 协程A阻塞到channel处，阻塞是带超时的；
2. 协程B往channel追加数据时，刚好协程A阻塞超时，即有线程（线程1）会执行定时器超时函数中的CancelWait；
3. channel追加数据时会唤醒协程A，即执行wakeup动作（线程2）；

上述场景中，协程A并没有被执行，但可以有线程对协程A相关的BlockObject进行并发操作

**Comment by yyzybb537** [comment]
这里有一个隐含的同步：wait_queue_
Wakeup时要从这个队列中pop出来才能执行，CancelWait时要从这个队列中erase后才能执行，这两个操作必然只有一个能成功，所以不存在并行
