### ISSUE TITLE
error: format '%d' expects argument of type 'int', but argument 5 has type 'co::TaskState' 

### ISSUE THREAD

**Issue by ongbe** [yyzybb537/libgo#5]
libgo/src/processer.cpp:69:9: note: in expansion of macro 'DebugPrint'
         DebugPrint(dbg_switch, "leave task(%s) state=%d", tk->DebugInfo(), tk->state_);
         ^
libgo/src/processer.cpp: In member function 'void co::Processer::CoYield(co::ThreadLocalInfo&)':
libgo/src/scheduler.h:21:68: error: format '%d' expects argument of type 'int', but argument 5 has type 'co::TaskState' [-Werror=format=]

uname -a
Linux 4.2.0-1-686-pae #1 SMP Debian 4.2.6-3 (2015-12-06) i686 GNU/Linux

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i586-linux-gnu/5/lto-wrapper
Target: i586-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 5.3.1-6' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --with-arch-32=i586 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i586-linux-gnu --host=i586-linux-gnu --target=i586-linux-gnu
Thread model: posix
gcc version 5.3.1 20160114 (Debian 5.3.1-6)

**Comment by ongbe** [comment]
libgo/src/processer.cpp:-1: In member function 'void co::Processer::CoYield(co::ThreadLocalInfo&)':
如下修改是否妥当，添加(int)
DebugPrint(dbg_yield, "yield task(%s) state=%d", tk->DebugInfo(), (int)tk->state_);

**Comment by yyzybb537** [comment]
感谢指正，这样改是OK的。

**Comment by yyzybb537** [comment]
已经修复
