### ISSUE TITLE
windows 下deque异常bug

### ISSUE THREAD

**Issue by xie1xiao1jun** [yyzybb537/libgo#52]
编译环境：vs 2017
使用tutorial下的sample8_multithread.cpp 的demo编译
其中修改 第41行
for (int i = 0; i < 8; ++i)
to
for (int i = 0; i < 108; ++i)
出现deque 断言
_DEBUG_ERROR("deque iterator not dereferencable");

**试过用线程安全队列解决，发现运行效率降了很多。**

**Comment by yyzybb537** [comment]
windows下的这套stl实现与gcc的有些差异，windows上仅供单线程测试，正式运行请放到linux上吧。

**Comment by hnwyllmm** [comment]
实际上deque在linux也不能这么用。
