### ISSUE TITLE
多个task的id多线程之下会不唯一

### ISSUE THREAD

**Issue by jinxianda** [yyzybb537/libgo#53]
co_sched.GetCurrentTaskID函数，每个task构造函数中的id以static变量s_id累加产生，但是s_id不是原子变量

**Comment by yyzybb537** [comment]
你是对的~  虽然这个id只是用来看log用的, 不会影响程序的正确性, 但是还是希望你能提交一个PR来修改这个bug

**Comment by yyzybb537** [comment]
已经有网友提交pr解决了
