### ISSUE TITLE
libgo 与 脚本混合编程（如 lua、python）

### ISSUE THREAD

**Issue by fananchong** [yyzybb537/libgo#54]
请教下大神， libgo可以和lua、python之类的脚本混合编程吗？

**Comment by jinxianda** [comment]
完全可以啊，我们就在用lua c++ libgo开发

**Comment by fananchong** [comment]
@jinxianda lua脚本应该不可以同时在多个线程中执行。  这样的话，如何利用libgo的优势，又可以使用lua脚本编程。 您能说下你们的做法大概吗？
