### ISSUE TITLE
请教libgo栈大小问题

### ISSUE THREAD

**Issue by fananchong** [yyzybb537/libgo#55]
go中 一个goroutine初始内存4K栈大小， 并可以动态扩展。  libgo看介绍默认2M栈大小， 主要想知道某协程栈空间增长大于2M后会发生什么？

**Comment by jinxianda** [comment]
栈溢出，整个程序崩溃

**Comment by fananchong** [comment]
还有2个问题请教
1) 是不是栈大小越小， 协议切换时，消耗越小
2) libgo最小栈大小可以多少？ 只取决于协程内变量总大小+逐级调用函数的栈大小总和吗

**Comment by jinxianda** [comment]
我们项目目前复杂点的程序也就设置了32K,暂时没发现有溢出现象

**Comment by yyzybb537** [comment]
栈的大小<=1MB时, 切换速度都是一样的.
推荐使用128K+的栈  会相对安全一些

**Comment by demiaowu** [comment]
有2个疑问：
1. 大于 1MB 会变慢吗 ？如果不会，那么考虑到虚拟内存机制，是不是可以分配更大的 stack 空间，反正 64 位机器的虚拟地址空间足够大
2. 看 libgo 当前会在 stack 后面跟一个 protect page，有一定作用，但是如果栈溢出超过这个 page，感觉还是不能检测出来 ？不知道理解对不对 ？
