### ISSUE TITLE
hook 读写文件系列 api

### ISSUE THREAD

**Issue by fananchong** [yyzybb537/libgo#56]
请教下 大神， 感觉会阻塞线程的地方，除了网络读写 还有就是本地磁盘读写。 是否可以这样认为：把 读写文件系列系统api也 hook后，可以达成不使用co_wait，协程不会阻塞线程。

**Comment by yyzybb537** [comment]
OS并没有提供一套完善的异步读写文件的API，所以暂时不做这方面的支持

**Comment by fawdlstty** [comment]
Windows和Linux已经提供了完善文件异步读写API，目前gayhub上面也有跨平台文件异步读写库，比如
https://github.com/ned14/afio
可以不做hook，但提供一个与框架统一的异步读写接口也是挺好的

**Comment by fawdlstty** [comment]
Windows上文件异步写API为WriteFileEx，其他操作类似，这类除了文件之外，设备、硬件、驱动也通过这类API访问，直接HOOK感觉不太好
