### ISSUE TITLE
ubuntu 16.04 + boost 1.64 编译错误

### ISSUE THREAD

**Issue by SimonML** [yyzybb537/libgo#58]
是暂时不支持boost1.64吗？

**Comment by skyformat99** [comment]
这个和boost没有关系吧？

**Comment by skyformat99** [comment]
希望作者能够不依赖boost就好了。
boost太大了，麻烦。
依赖越少越好。

**Comment by SimonML** [comment]
CMake警告:
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  third_party/libgo/boost.cmake:7 (find_package)
  third_party/libgo/CMakeLists.txt:28 (include)

Make错误提示：
In file included from /home/simon/libgonet/third_party/libgo/libgo/ctx_boost_context/context.h:4:0,
                 from /home/simon/libgonet/third_party/libgo/libgo/context.h:73,
                 from /home/simon/libgonet/third_party/libgo/libgo/scheduler.h:3,
                 from /home/simon/libgonet/third_party/libgo/libgo/coroutine.h:2,
                 from /home/simon/libgonet/libgonet/config.h:34,
                 from /home/simon/libgonet/libgonet/abstract.h:2,
                 from /home/simon/libgonet/libgonet/abstract.cpp:1:
/home/simon/libgonet/third_party/libgo/libgo/ctx_boost_context/context_v2.h:65:39: error: ‘execution_context’ in namespace ‘boost::context’ does not name a template type
             typedef ::boost::context::execution_context<void> context_t;
                                       ^~~~~~~~~~~~~~~~~

**Comment by jinxianda** [comment]
用1.63 或者直接用linux系统自带的，本来就可以不依赖boost,就是性能低点

**Comment by SimonML** [comment]
谢谢大神的回复。cmake的警告我已经解决，是cmake自带的findboost只检查到1.62, 已经解决。暂时未用boost编译通过, -DUSE_BOOST_CONTEXT=OFF -DUSE_BOOST_CORUTINE=OFF
 


Simon
 2017-08-04

 发件人： jinxianda发送时间： 2017-08-04 09:28收件人： yyzybb537/libgo抄送： SimonML; Author主题： Re: [yyzybb537/libgo] ubuntu 16.04 + boost 1.64 编译错误 (#58)用1.63 或者直接用linux系统自带的，本来就可以不依赖boost,就是性能低点

**Comment by skyformat99** [comment]
能不能直接把boost.context的相关的代码拷贝过来，放入系统？
或者修改一下放入系统。
这样减少依赖文件，而且性能也有。编译起来干净利落。

**Comment by jinxianda** [comment]
本来就只要编译boost.context啊，编译一个模块，非常快啊 @skyformat99

**Comment by skyformat99** [comment]
另外一个libcopp好像直接把boost移植进去了。
有没有可能也弄进去libgo里面。

**Comment by zagnix** [comment]
boost_1_59_0 用的比较好。

**Comment by yyzybb537** [comment]
boost最新的1.67已经支持了
