### ISSUE TITLE
编译sample2_yield.cpp + 静态链接 + 执行

### ISSUE THREAD

**Issue by Clcanny** [yyzybb537/libgo#66]
+ 把sample2_yield.cpp拷贝到libgo文件夹之外
+ 编译命令：g++ -std=c++11 -g -Wall sample2_yield.cpp -Ilibgo/libgo/ -Ilibgo/libgo/linux -llibgo -llibgo_main -lboost_coroutine -lboost_context -lboost_system -lboost_thread -lpthread -llibgo -llibgo_main -lboost_coroutine -lboost_context -lboost_system -lboost_thread -lpthread -static -static-libgcc -static-libstdc++
+ 动态链接可以正常执行
+ 不使用co_main而使用main，静态链接不会出现问题
+ 使用gdb调试，start之后直接抛出异常，没办法到main函数入口点

详细报告在：https://github.com/Clcanny/Notes/blob/master/libgo/TutorialOfLibgo/TutorialOfLibgo.md

**Comment by Clcanny** [comment]
发现：无论是`main`还是`co_main`都需要存在一个`thread_group`类型的变量才能正常静态链接／运行。

**Comment by yyzybb537** [comment]
首先建议不要使用 -I这种方式， 而是把libgo通过make install安装到系统目录里来include，当然这不影响结果。
1.会出现链接错误是因为gcc静态链接的向后查找机制，libgo_main是依赖于libgo的，所以链接选项中应该把-llibgo_main放在-llibgo的前面！
2.运行时错误是因为gcc的thread相关导致的问题，你可以尝试把-lpthread改为-pthread来解决问题，详细原因参见gcc manpage.

**Comment by Clcanny** [comment]
您好！感谢回复：
1. 链接的问题已经解决了（无论是调整顺序还是把库重复一遍）
2. -pthread没有解决运行时的问题

**Comment by yyzybb537** [comment]
我比较好奇为什么你不使用libgo里面的cmake来编译教程代码呢？

**Comment by yyzybb537** [comment]
g++ -std=c++11 sample2_yield.cpp -llibgo_main -llibgo -lboost_coroutine -lboost_context -lboost_thread -lboost_system -ldl -pthread -static -static-libstdc++
这是我刚刚测试使用编译命令，你可以试一下

**Comment by Clcanny** [comment]
额，因为CMake好像是用动态链接的方式来的
我只是很好奇为什么会有这种奇怪的现象
至少在g++ (Debian 6.3.0-18) 6.3.0 20170516 + debian 9下还是不行
有可能是debian或者g++的bug
一个会被优化掉的变量不应该对运行时行为产生影响

多谢！
