### ISSUE TITLE
请问有与gperftools的-ltcmalloc 一起使用过吗？

### ISSUE THREAD

**Issue by mlkt** [yyzybb537/libgo#69]
请问libgo有与gperftools一起链接使用过吗？有没有什么问题？
链接gperftools的-ltcmalloc 之后内存分配性能比较好

话说libgo现在还在生产环境上使用吗？

**Comment by bigbao9494** [comment]
楼主用gperftools 进行过libgo性能分析？

**Comment by yyzybb537** [comment]
生产环境中我们是搭配tcmalloc来使用的
