### ISSUE TITLE
libgo性能问题

### ISSUE THREAD

**Issue by bigbao9494** [yyzybb537/libgo#70]
你好，我在使用libgo做协程切换测试的时候使用性能分析工具分析了一下libgo的性能
发现如下现象：

函数名	调用数	已用非独占时间百分比	已用独占时间百分比	平均已用非独占时间	平均已用独占时间	模块名
<lambda_90f6debc7fcf34860066f531e8cc5f6b>::operator()	1	99.97	8.92	12,601.52	1,124.35	switch.t.exe

原因：
进入用户函数时只调用了一次Task::task_cb函数中的this->fn_()占用比却高达8.92，如果频繁地产生协程然后协程又快速结束这样岂不是会形成瓶颈

根据这样推测进行了测试，发现性能出现极大的下降，下降到只有原来的 1/20：
我测试的环境是vs2015,win7

//不停地创建协程，同时只有一个协程
void task_test()
{
	++counter[0];
	go task_test;
}
int main()
{
	go task_test;
	co_sched.RunLoop();
}

**Comment by yyzybb537** [comment]
没太看懂你的问题
请问你这个1/20的数字  是哪两种情况对比得出的？

**Comment by bigbao9494** [comment]
这是正常情况:
void task_test()
{
    for(;;)
    {
        ++counter[0];
         co_yield;
    }
}
int main()
{
go task_test;
co_sched.RunLoop();
}
怕是下降到只有原来1/20的情况：
void task_test()
{
++counter[0];
go task_test;
}
int main()
{
go task_test;
co_sched.RunLoop();
}

两者最大的区别就是一个在不停地创建协程，另一个只创建了2个协程，
测试它们切换的性能。

**Comment by bigbao9494** [comment]
我再次做了确认，我把TaskF修改成函数指针，而不是原来的std::function，使用switch测试提升了30万次以上(单线程情况测试)

**Comment by yyzybb537** [comment]
1.很遗憾的告诉你，libgo是为linux设计的，在win上达不到性能最佳。
linux上使用boost编译，可以达到每秒千万次级的切换速度。

2.协程switch的速度一定是比协程创建速度要慢的，这个是毋庸置疑的，因为协程创建需要一些内存malloc，而switch只需要push/poll寄存器即可。

3.std::function那个点，基本上没可能成为一个项目中的性能瓶颈的。

**Comment by bigbao9494** [comment]
现在问题感觉是在std::function上，和系统没有关系吧？
我就是想确认一下std::function是否会有影响，因为我单独写个程序来测试function调用，函数参数传递层次模拟相同但是也没有出现高的占比。根据性能分析结果和测试结果来看，这点在libgo上确实有这样的现象，就是不明白到底问题是出在哪儿。
我觉得这点在linux下可能会有同样的问题。

**Comment by yyzybb537** [comment]
等你的项目真正碰到性能瓶颈，再考虑优化问题吧
过早的优化和盲目的猜测优化，都不会有什么好结果

**Comment by bigbao9494** [comment]
“3.std::function那个点，基本上没可能成为一个项目中的性能瓶颈的。”
我觉得业务逻辑是有可能会出现这种需求的，比如说客户端有很多的短连接时就会出现。

**Comment by yyzybb537** [comment]
业务逻辑会远远大于一个std::function

**Comment by bigbao9494** [comment]
业务中会出现非常频繁地   go xxx; --> xxx函数结束   --> go xxx;  --> xxx函数结束
这种 情况 ，这样就是问题了。

**Comment by yyzybb537** [comment]
那你可以尝试写一个完整的webserver，做一个性能测试看看

**Comment by bigbao9494** [comment]
好吧，麻烦帮我看一下另外一个编译问题：https://github.com/yyzybb537/libgo/issues/71
