### ISSUE TITLE
linux编译问题

### ISSUE THREAD

**Issue by bigbao9494** [yyzybb537/libgo#71]
没有开启ENABLE_BOOST_CONTEXT和ENABLE_BOOST_COROUTINE选项，没有使用boost。

cmake .. -DDISABLE_HOOK=ON
make
disable_hook.cpp:12:36: fatal error: libgo/linux_glibc_hook.h: 没有那个文件或目录

不关闭HOOK时编译是能够通过的，但是我在测试程序中使用libgo.a时出现下面错误

16:17:35 **** Build of configuration Debug for project test_libgo ****
make all 
Building file: ../src/switch.cpp
Invoking: GCC C++ Compiler
g++ -I/home/libgo/libgo -I/home/libgo/libgo/libgo/linux -I/home/libgo/libgo/libgo/ctx_ucontext -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"src/switch.d" -MT"src/switch.o" -o "src/switch.o" "../src/switch.cpp"
Finished building: ../src/switch.cpp
 
Building file: ../src/test_libgo.cpp
Invoking: GCC C++ Compiler
g++ -I/home/libgo/libgo -I/home/libgo/libgo/libgo/linux -I/home/libgo/libgo/libgo/ctx_ucontext -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"src/test_libgo.d" -MT"src/test_libgo.o" -o "src/test_libgo.o" "../src/test_libgo.cpp"
Finished building: ../src/test_libgo.cpp
 
Building target: test_libgo
Invoking: GCC C++ Linker
g++ -L/home/libgo/libgo/build -pthread -o "test_libgo"  ./src/switch.o ./src/test_libgo.o  /home/libgo/libgo/build/liblibgo.a 
/home/libgo/libgo/build/liblibgo.a(linux_glibc_hook.cpp.o)：在函数‘co::coroutine_hook_init()’中：
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1342：对‘__readv’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1344：对‘__recvfrom’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1345：对‘__recvmsg’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1347：对‘__writev’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1349：对‘__sendto’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1350：对‘__sendmsg’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1351：对‘__libc_accept’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1354：对‘__sleep’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1359：对‘__ioctl’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1360：对‘__getsockopt’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1361：对‘__setsockopt’未定义的引用
makefile:45: recipe for target 'test_libgo' failed
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1362：对‘__dup’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1364：对‘__dup3’未定义的引用
/home/libgo/libgo/libgo/linux/linux_glibc_hook.cpp:1365：对‘__new_fclose’未定义的引用
collect2: error: ld returned 1 exit status
make: *** [test_libgo] Error 1

16:17:37 Build Finished (took 1s.866ms)

**Comment by yyzybb537** [comment]
baidu 静态链接

**Comment by bigbao9494** [comment]
我设置了对libgo.a的静态链接的啊，如果没有设置的话是报libgo中其它函数连接错误。

**Comment by bigbao9494** [comment]
这里：g++ -L/home/libgo/libgo/build -pthread -o "test_libgo"  ./src/switch.o ./src/test_libgo.o  /home/libgo/libgo/build/liblibgo.a

**Comment by yyzybb537** [comment]
我在ReadMe中写了静态链接的使用方式啊：
g++ -std=c++11 test.cpp -llibgo -static -static-libgcc -static-libstdc++
