### ISSUE TITLE
协程共享socket问题

### ISSUE THREAD

**Issue by bigbao9494** [yyzybb537/libgo#72]
请问一下linux中开启多线程时，同一个socket能否在多个协程中使用，比如：

int socket1;
void read_function()
{
	for(;;)
		recv(socket1);
}
void write_function()
{
	for(;;)
		send(socket1);
}
int main()
{
	go read_function;
	go write_function;
	下面使用多个线程
	......
}

**Comment by hnwyllmm** [comment]
协程的概念是轻量级线程，多线程中使用同一个socket，需要加锁，那么多个协程中使用同一个socket，一样的要加锁。socket函数本身不会保证多线程安全。
不过有些socket，比如TCP，是全双工的，读写不会有冲突，就是一个线程读，另一个线程写，他们之间不需要加锁

**Comment by birdwyx** [comment]
多线程访问同一个socket是安全的。 不仅如此，所有系统调用-linux/windows - 都是线程安全的。在协程中使用也是一样，都不需要加锁。

**Comment by bigbao9494** [comment]
其实我不是想问同一socket在多线程编程的问题，我是看到libgo的设计中好像是为了实现同一socket可以存在于不同task看，因为多线程调度不同task可能会同时在不同线程下执行。
libgo的设计成：同一socket只能同时存在于一个epoll_fd上，如果这个socket是在多个task中进行了read/write，那么也只有一个线程会对这个socket进行epoll_wait。
这样就会为了实现“共享socket”的功能而增加许多的线程同步的操作，难道“共享socket”这样的需求就真的是非常需要的吗？这种需要是否常见？我个人感觉这种需要有点奇葩，是否可以取消这种需求，这样也许可以提升多线程性能。请各位大神指点迷津啊！！ @yyzybb537

**Comment by birdwyx** [comment]
对于这个问题 （多个task对socket 进行read/write, 而会产生更多线程切换）。其实是设计者yyzybb537才有发言权
但我说下我的理解： 对于”共享socket“我不认为设计者有意为之，一个task可以由多个线程去调度 （worksteal算法），是为负载均衡而做的设计，而不是为了"共享socket", ”共享socket“只是负载均衡的一个结果。
这样是否会产生更多线程切换？ 的确会，但是否值得或者需要解决这个问题，是需要研究的，可以实测一下看有多大性能影响。

**Comment by birdwyx** [comment]
对于这个问题 （多个task对socket 进行read/write, 而会产生更多线程切换）。其实是设计者yyzybb537才有发言权
但我说下我的理解： 对于”共享socket“我不认为设计者有意为之，一个task可以由多个线程去调度 （worksteal算法），是为负载均衡而做的设计，而不是为了"共享socket", ”共享socket“只是负载均衡的一个结果。
这样是否会产生更多线程切换？ 的确会。但这是否一个大问题，是否值得解决这个问题，是需要研究的，可以实测一下看有多大性能影响。

**Comment by bigbao9494** [comment]
”共享socket“不是“一个task可以由多个线程去调度 ”，而是一个FD可以同时由多个task使用，比如task1.read(fd),task2.write(fd)，这样就会导致同一个fd可能在2个线程中同时使用（因为2个task分别在不同线程中），这样对这个fd的竞争就出来了，增加了更多的同步。

**Comment by bigbao9494** [comment]
我对go和libgo做过一个简单的性能测试：都实现了一个server做pingpong
1、go_server使用1个核心,libgo使用1个线程，也就是都使用1个线程来处理
2、go_server使用2个核心,libgo使用2个线程，也就是都使用2个线程来处理
第1种情况下go和libgo性能相关不大。第2种情况下libgo明显弱于go，比如1个线程时它们的次数都是
每秒5万次，2个线程时go=9万次 libgo=6万次，go在多线程下的处理能力能和多出的线程数正比，但是
libgo却远不及理论值（10万次）。所以才有了上面分析的原因。希望大家一起来讨论一下。

**Comment by yyzybb537** [comment]
1.同一socket只能同时存在于一个epoll_fd上，这个不是我一定要这样设计，而是linux系统的推荐方式；如果一个socket由多个epoll同时监听，那么会有非常复杂的问题产生，把简单问题复杂化显然不是一个好设计
2. 关于”共享socket“的问题，@hnwyllmm 的回答我认为非常经典，也非常恰当
3. 关于多线程性能的问题，go的线程调度相比libgo的worksteal而言更加惰性一点，在此的消耗也会更少一点，毕竟个人精力有限比不得google大厂人才济济。
libgo关闭worksteal，手动把链接分配到指定线程去跑，性能也可以接近线性增长

**Comment by yyzybb537** [comment]
这个issue先不关了，后面有时间可以再做一做多线程性能调优
