### ISSUE TITLE
FileDescriptorCtx问题

### ISSUE THREAD

**Issue by bigbao9494** [yyzybb537/libgo#73]
FileDescriptorCtx::lock_的类型
为什么多线程时要使用mutex，而不使用LFLock的多线程版本呢？
其它地方在多线程做保护的时候也在使用LFLock啊，为什么这里要换成mutex呢？

**Comment by jinxianda** [comment]
粒度太大，不适合用自旋锁啊

**Comment by bigbao9494** [comment]
你是说LFLock的粒度太大了所以要使用mutex？
那其它地方为什么又要使用LFLock而不使用mutex呢？
真心不懂啊。求指点。

**Comment by yyzybb537** [comment]
自旋锁适用于不会切换内核态、且比较简短的纯用户态代码
fd-ctx那里有很多系统调用，不太适合用自旋锁
