### ISSUE TITLE
希望添加windows下的mingw支持

### ISSUE THREAD

**Issue by zynfly** [yyzybb537/libgo#74]
RT.

mingw或者cygwin或者msys2。

已经抛弃vs好多年了。

**Comment by hnwyllmm** [comment]
自己做个代码兼容PR怎么样？

**Comment by zynfly** [comment]
没人响应。 我已经做好了。。。https://github.com/zynfly/libgo

**Comment by yyzybb537** [comment]
可以提交一个pr来看看
