### ISSUE TITLE
线程与协程的关系

### ISSUE THREAD

**Issue by hnwyllmm** [yyzybb537/libgo#75]
如果使用多线程模式，先创建线程后再创建task会有问题吗？我看到Processer.AddTaskRunnable是线程不安全的，多个线程操作Processer.runnable_list_会有问题。
我想要这种模式：
1. 任务个数不是确定的，需要无限循环接收客户端发的消息
2. 创建多个线程执行task，以利用多CPU的优势
3. 使用random或者robin算法，禁用steal算法，这样就有了线程亲和性，但是损失了多个线程间的均衡；
按照我对代码的理解，需要在创建的线程中这么做：
co_sched.Run();  // 创建一个新的Processer
go task // 可能有多个
co_sched.RunLoop() // or co_sched.RunUntilNoTask()

这种代码感觉比较怪，能不能提供一种更方便的接口，或者我对代码理解有误，有正确的写法？

**Comment by yyzybb537** [comment]
1.runnable_list_ 在当前有限的几种使用方式上  是线程安全的
2.创建线程后再创建task是完全ok的，也是推荐的做法
3.你的理解确实有误，Run和RunLoop是主逻辑循环接口，其后不应再有其他代码。使用方式上类似于asio的io_service.run();

**Comment by hnwyllmm** [comment]
多谢大神，完美解决
