### ISSUE TITLE
是否可以增加协程切换hook？ 已经在私有分支实现，如果ok，我提交pull request

### ISSUE THREAD

**Issue by birdwyx** [yyzybb537/libgo#76]
场景描述：
直接hook 系统调用，支持第三方库异步化，是一个非常好的功能。 问题是，部分第三方库已经深度使用全局变量或者TLS，这使得这些第三方不可能和libgo一起使用。而这部分第三方库，可能没有源码，或者有源码也因各种原因不能修改。。。

一个例子是我目前在做的，预备开源项目： phpgo，即在php上实现go routine。实现方式是以php扩展形式提供go 核心部分（基于libgo协程库，基本就是封装libgo包含的部分功能，感谢libgo！），问题是，php 5也好7也好，主程序部分代码都大量使用TLS，而我们是不可能轻易修改php主程序代码的。

一个解决方案是：
在协程切入的时候，保留scheduler相关全局变量或TLS，切换成协程现场，在协程切出保留协程全局变量TLS，切换成scheduler现场，而我们也是这么做的。我们在Scheduler 的TaskListener增加两个hook： SwapIn hook和SwapOut hook， 在hook中做相应的保存，恢复现场操作。

我们fork了libgo并做了相应改动并使用在phpgo项目中，目前phpgo小范围运行稳定。

请求事项：
我们认为能增加协程切换hook可以解决相当一部分类似的问题， 是一个善莫大焉的事 :)  所以请求
在Scheduler::TaskListener增加两个hook： SwapIn hook和SwapOut hook。 

妥否？ 恳请回复。

**Comment by yyzybb537** [comment]
欢迎贡献
请先提交PR给我看一下  我们可以一起讨论一下实现方式

**Comment by yyzybb537** [comment]
欢迎加入Q群 296561497  一起讨论

**Comment by bigbao9494** [comment]
能否说说讨论结果啊？？

**Comment by bigbao9494** [comment]
yyzybb537顺便帮我看看另外一个问题吧https://github.com/yyzybb537/libgo/issues/72

**Comment by birdwyx** [comment]
这两天没上来， 看到yyzybb537回复， 我就放心了。 我加群具体聊一下。

**Comment by birdwyx** [comment]
对于这个问题 （多个task对socket 进行read/write, 而会产生更多线程切换）。 

其实是设计者yyzybb537才有发言权 
我只是说下我的理解： 对于”共享socket“我不认为设计者有意为之，一个task可以由多个线程去调度 （worksteal算法），是为负载均衡而做的设计，而不是为了"共享socket", ”共享socket“只是负载均衡的一个结果。
这样是否会产生更多线程切换？ 的确会，但是否值得或者需要解决这个问题，是需要研究的，可以实测一下看有多大性能影响。

**Comment by mlkt** [comment]
除了TLS 还有锁的问题
