### ISSUE TITLE
为什么不hook epoll_wait ？

### ISSUE THREAD

**Issue by mlkt** [yyzybb537/libgo#80]
如果不hook epoll_wait 就不能和libevent之类的本来就使用异步的框架一起使用了

**Comment by yyzybb537** [comment]
epoll_wait的hook遇到了一些难题，glibc并没有对这个syscall做alias，静态链接的情况下hook后没法找到可替代原有功能的函数（没有提供__epoll_wait这样一个版本的alias）
暂行的解决方式时提供了一个libgo_epoll_wait接口，可以修改libevent源码，改为使用这个接口来配合使用。

**Comment by yyzybb537** [comment]
如果有hook的方案，欢迎分享一下

**Comment by mlkt** [comment]
https://github.com/Zeex/subhook
静态链接的时候用这个
