### ISSUE TITLE
udp socket 收到数据无法返回

### ISSUE THREAD

**Issue by dearbird** [yyzybb537/libgo#83]
wireshark 抓包，确认包有到达本机
gdb attach 进去，确认epoll线程有在跑，同时另一个tcp的socket是可以收到数据的。

查看 /proc/net/udp
866: 00000000:2328 00000000:0000 07 00000000:00201000 00:00000000 00000000     0        0 176774 2 ffff880139663740 7937300 
可以发现tx_queue 已经满了，包都被丢弃了。

怀疑epoll实现有bug， fd没有被放回epoll set中，或者相应的event没有设置

另外，该udp socket是可以正常发包的。

**Comment by dearbird** [comment]
@yyzybb537 
linux_glibc_hook.cpp: 572 会把fd_ctx设为不可读
在udp场景下，n < buflen总是成立，所以每读一个包都会将ctx设为不可读
这是否有问题?

**Comment by yyzybb537** [comment]
试过libgonet吗

**Comment by dearbird** [comment]
看过libgonet，感觉封装的比较复杂，我的业务逻辑仅是代理转发而已，之间在libgo上实现。

我目前先加大了socket buffer，再观察看看。

**Comment by yyzybb537** [comment]
libgonet是商用过的稳定项目，应该会比未经测试的更靠谱一点

**Comment by dearbird** [comment]
#78  这个问题描述跟我的现象类似，也是epoll没有返回。
我试着关闭worksteal再测测看

**Comment by dearbird** [comment]
其余代码不变，关闭 worsteal之前，跑几个小时就会出现issue描述的现象，关闭之后，跑了整个周末没有重现。
worksteal 与 epoll的配合可能存在问题。
@yyzybb537

**Comment by jinxianda** [comment]
@yyzybb537 你好 能具体指出下再次run需要哪些tls-epoll相关操作吗？看源码每个fd都是跟某个epoll fd绑定死的 就算被steal了再另一个线程run好像也不破坏它们的绑定关系。
