### ISSUE TITLE
你好，编译的时候遇到这样的问题，能帮忙看下吗

### ISSUE THREAD

**Issue by dwroy** [yyzybb537/libgo#84]
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1342: undefined reference to `__readv'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1343: undefined reference to `__recv'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1344: undefined reference to `__recvfrom'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1345: undefined reference to `__recvmsg'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1347: undefined reference to `__writev'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1349: undefined reference to `__sendto'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1350: undefined reference to `__sendmsg'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1351: undefined reference to `__libc_accept'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1354: undefined reference to `__sleep'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1359: undefined reference to `__ioctl'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1360: undefined reference to `__getsockopt'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1361: undefined reference to `__setsockopt'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1362: undefined reference to `__dup'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1364: undefined reference to `__dup3'
/root/libgo/libgo/linux/linux_glibc_hook.cpp:1365: undefined reference to `__new_fclose'

**Comment by hnwyllmm** [comment]
怎么编译的？链接库怎么链的？

**Comment by dwroy** [comment]
后来该用动态连接库，弄好了
