### ISSUE TITLE
accept hook无效问题

### ISSUE THREAD

**Issue by ustcr7** [yyzybb537/libgo#88]
void accept_client_routine()
{
    for(;;)
    {
        fd = accept(); //如果没有客户端连接,这应该会阻塞,但是CPU并没有让出来, 导致check_routine无法使用
        go client_routine
    }
}

void check_routine()
{
   for(;;)
   {
        sleep(1);
        do some work;
   }
}

int main()
{
    go accept_client_routine;
    go check_routine;
    while (!g_Scheduler.IsEmpty()) {
        g_Scheduler.Run();
    }
}

accept模式不是默认hook的吗。 为什么上述场景，会导致线程阻塞？ 或者是使用方式不对？

**Comment by yyzybb537** [comment]
很可能是编译链接的方式不对，看看README上吧，需要先链接libgo。

**Comment by yyzybb537** [comment]
如果还不能解决，提供一下具体测试代码

**Comment by ustcr7** [comment]
链接了libgo ，我测试时，把accep换成sleep就可以让处CPU.
https://paste.ubuntu.com/p/wtQcst6yQD/

**Comment by ustcr7** [comment]
https://paste.ubuntu.com/p/x3dZdPTdT7/
这是整理后的代码，麻烦yyzy看下。 同样的echo_server routine,把accept换成sleep就能让出CPU。

**Comment by ustcr7** [comment]
确实是顺序问题，libgo放到最开始就可以了。。。
