### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by zhengshuxin** [yyzybb537/libgo#9]
使用 gcc5.3.0 编译时出现如下错误：
 make
Scanning dependencies of target libgo_dynamic
[  3%] Building CXX object CMakeFiles/libgo_dynamic.dir/libgo/co_rwmutex.cpp.o
[  6%] Building CXX object CMakeFiles/libgo_dynamic.dir/libgo/sleep_wait.cpp.o
[ 10%] Building CXX object CMakeFiles/libgo_dynamic.dir/libgo/task.cpp.o
[ 13%] Building CXX object CMakeFiles/libgo_dynamic.dir/libgo/block_object.cpp.o
[ 17%] Building CXX object CMakeFiles/libgo_dynamic.dir/libgo/timer.cpp.o
[ 20%] Building CXX object CMakeFiles/libgo_dynamic.dir/libgo/co_mutex.cpp.o
[ 24%] Building CXX object CMakeFiles/libgo_dynamic.dir/libgo/thread_pool.cpp.o
[ 27%] Building CXX object CMakeFiles/libgo_dynamic.dir/libgo/processer.cpp.o
In file included from /home/zsx/download/libgo/libgo/task.h:8:0,
                 from /home/zsx/download/libgo/libgo/processer.h:2,
                 from /home/zsx/download/libgo/libgo/processer.cpp:1:
/home/zsx/download/libgo/libgo/processer.cpp: In member function ‘void co::Processer::CoYield(co::ThreadLocalInfo&)’:
/home/zsx/download/libgo/libgo/config.h:55:107: error: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘co::TaskState’ [-Werror=format=]
                     ::co::codebug_GetCurrentProcessID(), ::co::codebug_GetCurrentThreadID(), ##__VA_ARGS__); \
                                                                                                           ^
/home/zsx/download/libgo/libgo/processer.cpp:120:5: note: in expansion of macro ‘DebugPrint’
     DebugPrint(dbg_yield, "yield task(%s) state=%d", tk->DebugInfo(), tk->state_);
     ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/libgo_dynamic.dir/libgo/processer.cpp.o] Error 1
make[1]: *** [CMakeFiles/libgo_dynamic.dir/all] Error 2
make: *** [all] Error 2

**Comment by kkHAIKE** [comment]
(int)(tk->state_)
试试？

**Comment by yyzybb537** [comment]
可以的，已经修正了， 你可以拉取最新代码重新试试
