### ISSUE TITLE
是否可以增加一个对协程优先级的设定

### ISSUE THREAD

**Issue by Archer-Hidden** [yyzybb537/libgo#91]
最近一周对libgo的学习，感触颇多。 同时也想到了一个可能可以的新功能？

场景： 海量协程需要共享一个有限的资源集合。 比如 一个数据库的链接池，且链接池容量远小于协程数量。因为，在运行中，只有获得了资源的协程才能继续运行，其他协程都需要等待资源被释放。所以，这就导致协程调度过程中，大部分时间被消耗在切换协程和等待中，实际运行时间很少（针对获取了资源的协程而言）。

因此，我想是否可以对协程做一个优先级的调整，让调度器优先调用优先级高（已经获取了资源）的协程。

（ps 我并不清楚这是否违反协程的应用场景）

**Comment by yyzybb537** [comment]
等待的协程，会设置为block状态，并不会被调度。

**Comment by hnwyllmm** [comment]
我觉得可以有，不过这样就会变得更复杂了，向内核调度器靠近。
