### ISSUE TITLE
关于3.0重构的建议

### ISSUE THREAD

**Issue by dearbird** [yyzybb537/libgo#92]
@amagri @yyzybb537 

1. 目前功能加的越来越多，如cls，defer，listener hook等，这些功能是否可以禁用（不编译）
2. 目前有提供coroutine版的mutex，能否提供与std::condition 相同语义的cond

**Comment by yyzybb537** [comment]
3.0的重构目的之一就是解耦这些东西，把这些都做成可拔插的，具体的拔插方式待定。
另一个目的就是解耦之后便于做一些更优的调整，比如优化协程调度性能、对多线程更好的支持、解决队头阻塞效应、更简单的netio等等。

**Comment by yyzybb537** [comment]
channel就是类std::condition语义~~~  只是没有notify_all，后续也会做的更完善

**Comment by IronsDu** [comment]
请问一个项目（进程）里，是否可以在使用已有的异步网络库的同时，又引入libgo来使用其他同步网络driver（redis、mysql）？

**Comment by yyzybb537** [comment]
这是完全可以的， 事实上这正是3.0主要支持的特性之一. 
参见3.0分支的README

**Comment by yyzybb537** [comment]
3.0目前已经完成，待我补齐相关资料就会合到master分支

**Comment by yyzybb537** [comment]
已合入master分支， linux&macos系统可以使用了
