### ISSUE TITLE
如何实现socket读写超时？

### ISSUE THREAD

**Issue by dearbird** [yyzybb537/libgo#93]
man文档上写明，SO_RCVTIMEO对epoll是无效的。

目前是读协程有收到数据就更新时间戳，单独启一个协程遍历socket来检查时间戳。
但是遍历检查需要加锁，连接多了不太高效，虽然后面可以拆成小锁来优化，但是总感觉不是很漂亮。

我的问题是，libgo的hook下有什么其它思路吗？

**Comment by yyzybb537** [comment]
用SO_RCVTIMEO + 阻塞式socket即可

**Comment by dearbird** [comment]
有看到相关源码了，有设置SO_RCVTIMEO 时，每次poll会启用定时器。
还没有测试，不知道当收发包频繁时，每次增删定时器是不是会影响性能。
