### ISSUE TITLE
static compile error 

### ISSUE THREAD

**Issue by zag2017** [yyzybb537/libgo#94]
**compile command:**
`
g++ -std=c++11 venus_proxy_1.cpp -llibgo -lboost_coroutine -lboost_context -lboost_system -lboost_thread -lpthread -ldl -static -static-libgcc -static-libstdc++`

**_complie error:_**

_/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libc.a(poll.o): In function `__poll':
(.text+0x0): multiple definition of `__poll'_
//usr/local/lib/liblibgo.a(linux_glibc_hook.cpp.o):/home/zag/cpp/libgo/libgo/linux/linux_glibc_hook.cpp:526: first defined here
//usr/local/lib/liblibgo.a(linux_glibc_hook.cpp.o): In function `gethostbyaddr':
/home/zag/cpp/libgo/libgo/linux/linux_glibc_hook.cpp:699: warning: Using 'gethostbyaddr_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/liblibgo.a(linux_glibc_hook.cpp.o): In function `gethostbyname2':
/home/zag/cpp/libgo/libgo/linux/linux_glibc_hook.cpp:649: warning: Using 'gethostbyname2_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/liblibgo.a(linux_glibc_hook.cpp.o): In function `gethostbyname':
/home/zag/cpp/libgo/libgo/linux/linux_glibc_hook.cpp:597: warning: Using 'gethostbyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

**Comment by cSingleboy** [comment]
I've had the same mistake.

**Comment by cSingleboy** [comment]
我已经解决了，，我用的是codeblocks，ubuntu，并且我编译的都是静态库，程序中引用，也是静态连接方式：
link library处写上一条：liblibgo
右边other linker options写：
-W
-pthread
-static-libgcc
-static-libstdc++
注意： 不用连接boost静态库了；
