### ISSUE TITLE
请问虚拟内存栈是如何实现的

### ISSUE THREAD

**Issue by Archer-Hidden** [yyzybb537/libgo#95]
经过阅读代码，我发现libgo里的Stackalloctor直接使用了stl库自带的malloc和free来维护内存。不同的是加入了保护栈的分配和回收。

这在实现上基本和boost的fixedsize_stack这个allocator是一致的，也是使用了stl的malloc和free维护内存，除了保护栈的部分。 （https://www.boost.org/doc/libs/1_64_0/libs/context/doc/html/context/stack/fixedsize.html）

然而同样使用stl库管理内存的情况下，boost的stackallocator并没有虚拟内存栈的效果

所以，我想请教下libgo这个虚拟内存栈的概念是如何实现的 谢谢！

**Comment by yyzybb537** [comment]
都有的
