### ISSUE TITLE
ThreadPool

### ISSUE THREAD

**Issue by cSingleboy** [yyzybb537/libgo#96]
get()里为什么要弹出2次？

TPElemBase* ThreadPool::get()
{
    TPElemBase *elem = elem_list_.pop();
    if (elem) return elem;

    std::unique_lock<std::mutex> lock(cond_mtx_);
    while (elem_list_.empty())
        cond_.wait(lock);
        
    return elem_list_.pop();
}

**Comment by yyzybb537** [comment]
double-check
