### ISSUE TITLE
sample6_mutex.cpp 中的lambda copy capture

### ISSUE THREAD

**Issue by Archer-Hidden** [yyzybb537/libgo#97]
请问这里使用copy capture为什么不会引起编译器报错呢，co_mutex并没有copy constructor，理应会报错说找不到co_mutex 的copy constructor

 而且要捕获mutex的话，不是应该用reference  capture更合理吗

**Comment by yyzybb537** [comment]
copy constructor是编译器会帮忙生成的几个类成员函数之一
